# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b64f8e6a522d7bb41f5d56cf6a5f6cf7620f90e5bd5f85d98f97b952fcb07bcc61d9cde9ec3e5701cb801638f1e04528f0acf5beb0c1154af6e0ccbc9ad642c2

test:
  secret_key_base: 1948e413783bd20aa8d9892cfeb85a2cb7e8abbb7cc1396fdd5f346c53059c635260b96213372d2bb9be3f8ced539d1fc8e7b2dc37d065a35c6f3260d3f3af31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
